### ISSUE TITLE
Example program in README outdated?

### ISSUE THREAD

**Issue by Yvee1** [5outh/chaosbox#3]
Hello,

I noticed that the example program located in `example/Main.hs` works perfectly, but the one in the README gives type errors. I think the problem lies in the difference between `c <- readIORefWith (maybe p (lerp 0.05 p)) mousePositionRef` (working) and `c <- forIORef mousePositionRef $ maybe p (lerp 0.05 p)` (from readme, not working).

(PS. I used your chaosbox library before and it worked well, but there were always some things missing, especially a window where you can have user input and see an animation, which made me use JavaScript or Processing or something instead. Seeing this update and noticing you've implemented exactly that makes me excited to try doing some genart in Haskell again!)

Thanks for your work and making this open-source!

**Comment by 5outh** [comment]
Thanks for pointing this out! I've updated the example in the README with the one from `example/Main.hs`.

I've been working hard on the interactive component; I hope you like it! Just a heads up that I've been using the framework in its current form for a bit and the geometry API is going to get simpler. The whole `Transform2d` bit is a little too restrictive so you may see another bit of API churn there. I would love any input if you end up digging in and poking around with chaosbox.
