### ISSUE TITLE
HSV hue range inconsistency

### ISSUE THREAD

**Issue by Yvee1** [5outh/chaosbox#5]
Hi,

I noticed that the functions `setSourceHSV` and `setSourceHSVA` use different ranges for the hue argument. `setSourceHSV` expects hue to be between 0 and 1, while `setSourceHSVA` interprets hue as a value between 0 and 360.

Following the convention of the `Data.Colour` package, so letting hue be between 0 and 360, would make most sense I think and is also most intuitive.

**Comment by 5outh** [comment]
Thank you! Fixed in #11
