### ISSUE TITLE
Somewhat confusing naming in ChaosBox.Random

### ISSUE THREAD

**Issue by Yvee1** [5outh/chaosbox#7]
I noticed the function `normal` generates a _normal_ random variable. Then, wanting a _uniform_ random variable I looked at the `uniform` function. However, this is not what I expected it to be. Contrary to the `normal` function it samples from a collection instead of being a uniformly distributed random variable. Furthermore the function I was searching for seems to be missing in the module as far as I can see. Some possible ways to fix this issue that I could think of are listed below:

rename `uniform` to `sample`, and let `uniform a b =  sampleRVar (Random.uniform a b)`: 
\+ `sample` fits well with `sampleN`
\+ `uniform` is now a random variable like `normal`, `gamma`, `bernoulli`
\- `sample` is an existing function in Data.Random
\- would make changing `weighted` to `weightedSample` more logical

`uniformR a b = sampleRVar (Random.uniform a b)` or `getUniformR`:
\+ Fits with `getRandomR` from `Control.Monad.Random.Class`
\- looks like it's a different kind of function than `normal`, `gamma` etc.

`random a b = sampleRVar (Random.uniform a b)`:
\+ does not require any name changes of existing functions
\- very ambiguous

Obviously, it's entirely up to you to decide how you want to make your API.

**Comment by 5outh** [comment]
I like the `sample` nomenclature so I went that way. Thanks for your insight into the library, it's really helpful!

Fixed here: https://github.com/5outh/chaosbox/commit/df03b2aef2a54dc3af97c5eefd7431b00f289248
