### ISSUE TITLE
Rendering output to SVG

### ISSUE THREAD

**Issue by Yvee1** [5outh/chaosbox#9]
Hello again!

I have been playing around a little with SVGs, and I was wondering if functionality could be added for rendering an image from chaosbox to SVG. If I have a sketch `mySketch :: Render ()` then I can render this to an SVG like this:
```
main :: IO ()
main = 
  withSVGSurface "out.svg" 500 500 $ \surface -> do
    renderWith surface mySketch
    surfaceFinish surface
```
(this took me some time to figure out since it's a bit different from rendering to PNG)

Anyways, rendering a sketch of type `Generate ()` is not possible this way. As far as I can tell, the only way to do this would be to adapt the `runChaosBoxDirectly` function to use an SVG surface instead of a PNG one, and then also write a corresponding `saveImageWith` function for SVGs (since `surfaceFinish` needs to be used instead of `surfaceWriteToPNG`).

This is not ideal and would take some time to figure out, therefore I think it would be nice to add functionality for rendering different image types to the library. Alternatively, a way to easier extend the library to add something like this would also be a solution, but I wouldn't know how that could be done.

Something like the [haskell-chart library has](https://github.com/timbod7/haskell-chart/blob/551c25d9820252b895db957bf99a1f57573d99d5/chart-cairo/Graphics/Rendering/Chart/Backend/Cairo.hs#L167) would be a good solution I think. So adding an option `FileFormat` to `Opts` with the default being `PNG`, and then doing a case distinction when rendering to an image.

What do you think? I wouldn't mind helping implement this via a pull request.

PS. Rendering an existing SVG onto a cairo surface for use in a sketch was also something I was interested in and have been toying with briefly. I had significant trouble getting it to work since something like [svgcairo](https://hackage.haskell.org/package/svgcairo) uses cairo instead of gi-cairo, and adapting this to work with gi-cairo didn't succeed because I got compile errors saying there were errors in the C header files in glib. When I was about to give up I found [hs-librsvg](https://github.com/albertov/hs-librsvg) which had many fewer dependencies [and got that to work pretty easily with gi-cario](https://github.com/Yvee1/hs-librsvg). Just FYI in case you want to add functionality for rendering images to chaosbox.

**Comment by 5outh** [comment]
Closed by #14
